
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AWS CloudFormation Template for the Common resources'

Resources:
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Requests_Layer
      ContentUri: requests-layer/
      CompatibleRuntimes:
        - python3.8
        - python3.7
        - python3.9
        - python3.10
      Description: A layer that includes the requests library
      LicenseInfo: MIT

Outputs:
  RequestsARN:
    Description: Requests Layer ARN
    Value: !Ref RequestsLayer
    Export:
      Name: Requests
